---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.cpgtoacp.io
  resources:
  - careplanwriters
  - cpgingesters
  - sandboxrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.cpgtoacp.io
  resources:
  - careplanwriters/finalizers
  - cpgingesters/finalizers
  - sandboxrequests/finalizers
  verbs:
  - update
- apiGroups:
  - apps.cpgtoacp.io
  resources:
  - careplanwriters/status
  - cpgingesters/status
  - sandboxrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sonataflow.org
  resources:
  - sonataflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
