//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPGIngester) DeepCopyInto(out *CPGIngester) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPGIngester.
func (in *CPGIngester) DeepCopy() *CPGIngester {
	if in == nil {
		return nil
	}
	out := new(CPGIngester)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CPGIngester) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPGIngesterList) DeepCopyInto(out *CPGIngesterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CPGIngester, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPGIngesterList.
func (in *CPGIngesterList) DeepCopy() *CPGIngesterList {
	if in == nil {
		return nil
	}
	out := new(CPGIngesterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CPGIngesterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPGIngesterSpec) DeepCopyInto(out *CPGIngesterSpec) {
	*out = *in
	in.Ingestion.DeepCopyInto(&out.Ingestion)
	in.LLMAnalysis.DeepCopyInto(&out.LLMAnalysis)
	in.Assembly.DeepCopyInto(&out.Assembly)
	in.Delivery.DeepCopyInto(&out.Delivery)
	in.BFF.DeepCopyInto(&out.BFF)
	in.UI.DeepCopyInto(&out.UI)
	if in.Workflow != nil {
		in, out := &in.Workflow, &out.Workflow
		*out = new(WorkflowSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPGIngesterSpec.
func (in *CPGIngesterSpec) DeepCopy() *CPGIngesterSpec {
	if in == nil {
		return nil
	}
	out := new(CPGIngesterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPGIngesterStatus) DeepCopyInto(out *CPGIngesterStatus) {
	*out = *in
	in.WorkloadStatus.DeepCopyInto(&out.WorkloadStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPGIngesterStatus.
func (in *CPGIngesterStatus) DeepCopy() *CPGIngesterStatus {
	if in == nil {
		return nil
	}
	out := new(CPGIngesterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarePlanWriter) DeepCopyInto(out *CarePlanWriter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarePlanWriter.
func (in *CarePlanWriter) DeepCopy() *CarePlanWriter {
	if in == nil {
		return nil
	}
	out := new(CarePlanWriter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CarePlanWriter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarePlanWriterList) DeepCopyInto(out *CarePlanWriterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CarePlanWriter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarePlanWriterList.
func (in *CarePlanWriterList) DeepCopy() *CarePlanWriterList {
	if in == nil {
		return nil
	}
	out := new(CarePlanWriterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CarePlanWriterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarePlanWriterSpec) DeepCopyInto(out *CarePlanWriterSpec) {
	*out = *in
	in.PatientData.DeepCopyInto(&out.PatientData)
	in.LLMReasoning.DeepCopyInto(&out.LLMReasoning)
	in.DecisionEngine.DeepCopyInto(&out.DecisionEngine)
	in.FHIRGeneration.DeepCopyInto(&out.FHIRGeneration)
	in.FHIRServer.DeepCopyInto(&out.FHIRServer)
	in.BFF.DeepCopyInto(&out.BFF)
	in.UI.DeepCopyInto(&out.UI)
	in.MCP.DeepCopyInto(&out.MCP)
	in.DecisionService.DeepCopyInto(&out.DecisionService)
	if in.Workflow != nil {
		in, out := &in.Workflow, &out.Workflow
		*out = new(WorkflowSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarePlanWriterSpec.
func (in *CarePlanWriterSpec) DeepCopy() *CarePlanWriterSpec {
	if in == nil {
		return nil
	}
	out := new(CarePlanWriterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarePlanWriterStatus) DeepCopyInto(out *CarePlanWriterStatus) {
	*out = *in
	in.WorkloadStatus.DeepCopyInto(&out.WorkloadStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarePlanWriterStatus.
func (in *CarePlanWriterStatus) DeepCopy() *CarePlanWriterStatus {
	if in == nil {
		return nil
	}
	out := new(CarePlanWriterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentSpec) DeepCopyInto(out *ComponentSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentSpec.
func (in *ComponentSpec) DeepCopy() *ComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowSpec) DeepCopyInto(out *WorkflowSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowSpec.
func (in *WorkflowSpec) DeepCopy() *WorkflowSpec {
	if in == nil {
		return nil
	}
	out := new(WorkflowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadStatus) DeepCopyInto(out *WorkloadStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadStatus.
func (in *WorkloadStatus) DeepCopy() *WorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadStatus)
	in.DeepCopyInto(out)
	return out
}
