//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AITransparencySpec) DeepCopyInto(out *AITransparencySpec) {
	*out = *in
	if in.Reviewer != nil {
		in, out := &in.Reviewer, &out.Reviewer
		*out = new(ReviewerSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AITransparencySpec.
func (in *AITransparencySpec) DeepCopy() *AITransparencySpec {
	if in == nil {
		return nil
	}
	out := new(AITransparencySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactStoreSpec) DeepCopyInto(out *ArtifactStoreSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactStoreSpec.
func (in *ArtifactStoreSpec) DeepCopy() *ArtifactStoreSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPGIngester) DeepCopyInto(out *CPGIngester) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPGIngester.
func (in *CPGIngester) DeepCopy() *CPGIngester {
	if in == nil {
		return nil
	}
	out := new(CPGIngester)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CPGIngester) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPGIngesterList) DeepCopyInto(out *CPGIngesterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CPGIngester, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPGIngesterList.
func (in *CPGIngesterList) DeepCopy() *CPGIngesterList {
	if in == nil {
		return nil
	}
	out := new(CPGIngesterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CPGIngesterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPGIngesterSpec) DeepCopyInto(out *CPGIngesterSpec) {
	*out = *in
	out.Sandbox = in.Sandbox
	if in.ArtifactStore != nil {
		in, out := &in.ArtifactStore, &out.ArtifactStore
		*out = new(ArtifactStoreSpec)
		**out = **in
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(ObservabilitySpec)
		**out = **in
	}
	if in.LLM != nil {
		in, out := &in.LLM, &out.LLM
		*out = new(LLMConfigSpec)
		**out = **in
	}
	if in.CarePlanWriterRef != nil {
		in, out := &in.CarePlanWriterRef, &out.CarePlanWriterRef
		*out = new(PipelineReference)
		**out = **in
	}
	in.Ingestion.DeepCopyInto(&out.Ingestion)
	in.LLMAnalysis.DeepCopyInto(&out.LLMAnalysis)
	in.Assembly.DeepCopyInto(&out.Assembly)
	in.Delivery.DeepCopyInto(&out.Delivery)
	in.BFF.DeepCopyInto(&out.BFF)
	in.UI.DeepCopyInto(&out.UI)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPGIngesterSpec.
func (in *CPGIngesterSpec) DeepCopy() *CPGIngesterSpec {
	if in == nil {
		return nil
	}
	out := new(CPGIngesterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPGIngesterStatus) DeepCopyInto(out *CPGIngesterStatus) {
	*out = *in
	in.WorkloadStatus.DeepCopyInto(&out.WorkloadStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPGIngesterStatus.
func (in *CPGIngesterStatus) DeepCopy() *CPGIngesterStatus {
	if in == nil {
		return nil
	}
	out := new(CPGIngesterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPGIngestionComponentSpec) DeepCopyInto(out *CPGIngestionComponentSpec) {
	*out = *in
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPGIngestionComponentSpec.
func (in *CPGIngestionComponentSpec) DeepCopy() *CPGIngestionComponentSpec {
	if in == nil {
		return nil
	}
	out := new(CPGIngestionComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPGLLMAnalysisComponentSpec) DeepCopyInto(out *CPGLLMAnalysisComponentSpec) {
	*out = *in
	in.PythonComponentSpec.DeepCopyInto(&out.PythonComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPGLLMAnalysisComponentSpec.
func (in *CPGLLMAnalysisComponentSpec) DeepCopy() *CPGLLMAnalysisComponentSpec {
	if in == nil {
		return nil
	}
	out := new(CPGLLMAnalysisComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarePlanLLMReasoningComponentSpec) DeepCopyInto(out *CarePlanLLMReasoningComponentSpec) {
	*out = *in
	in.PythonComponentSpec.DeepCopyInto(&out.PythonComponentSpec)
	if in.Embedding != nil {
		in, out := &in.Embedding, &out.Embedding
		*out = new(EmbeddingSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarePlanLLMReasoningComponentSpec.
func (in *CarePlanLLMReasoningComponentSpec) DeepCopy() *CarePlanLLMReasoningComponentSpec {
	if in == nil {
		return nil
	}
	out := new(CarePlanLLMReasoningComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarePlanWriter) DeepCopyInto(out *CarePlanWriter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarePlanWriter.
func (in *CarePlanWriter) DeepCopy() *CarePlanWriter {
	if in == nil {
		return nil
	}
	out := new(CarePlanWriter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CarePlanWriter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarePlanWriterList) DeepCopyInto(out *CarePlanWriterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CarePlanWriter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarePlanWriterList.
func (in *CarePlanWriterList) DeepCopy() *CarePlanWriterList {
	if in == nil {
		return nil
	}
	out := new(CarePlanWriterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CarePlanWriterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarePlanWriterSpec) DeepCopyInto(out *CarePlanWriterSpec) {
	*out = *in
	out.Sandbox = in.Sandbox
	if in.ArtifactStore != nil {
		in, out := &in.ArtifactStore, &out.ArtifactStore
		*out = new(ArtifactStoreSpec)
		**out = **in
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(ObservabilitySpec)
		**out = **in
	}
	if in.LLM != nil {
		in, out := &in.LLM, &out.LLM
		*out = new(LLMConfigSpec)
		**out = **in
	}
	if in.FHIRTarget != nil {
		in, out := &in.FHIRTarget, &out.FHIRTarget
		*out = new(FHIRTargetSpec)
		**out = **in
	}
	if in.AITransparency != nil {
		in, out := &in.AITransparency, &out.AITransparency
		*out = new(AITransparencySpec)
		(*in).DeepCopyInto(*out)
	}
	in.PatientData.DeepCopyInto(&out.PatientData)
	in.LLMReasoning.DeepCopyInto(&out.LLMReasoning)
	in.DecisionEngine.DeepCopyInto(&out.DecisionEngine)
	in.FHIRGeneration.DeepCopyInto(&out.FHIRGeneration)
	in.FHIRServer.DeepCopyInto(&out.FHIRServer)
	in.BFF.DeepCopyInto(&out.BFF)
	in.UI.DeepCopyInto(&out.UI)
	in.MCP.DeepCopyInto(&out.MCP)
	in.DecisionService.DeepCopyInto(&out.DecisionService)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarePlanWriterSpec.
func (in *CarePlanWriterSpec) DeepCopy() *CarePlanWriterSpec {
	if in == nil {
		return nil
	}
	out := new(CarePlanWriterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarePlanWriterStatus) DeepCopyInto(out *CarePlanWriterStatus) {
	*out = *in
	in.WorkloadStatus.DeepCopyInto(&out.WorkloadStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarePlanWriterStatus.
func (in *CarePlanWriterStatus) DeepCopy() *CarePlanWriterStatus {
	if in == nil {
		return nil
	}
	out := new(CarePlanWriterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentSpec) DeepCopyInto(out *ComponentSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(v1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.ExtraProviders != nil {
		in, out := &in.ExtraProviders, &out.ExtraProviders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraEnv != nil {
		in, out := &in.ExtraEnv, &out.ExtraEnv
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentSpec.
func (in *ComponentSpec) DeepCopy() *ComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionServiceComponentSpec) DeepCopyInto(out *DecisionServiceComponentSpec) {
	*out = *in
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionServiceComponentSpec.
func (in *DecisionServiceComponentSpec) DeepCopy() *DecisionServiceComponentSpec {
	if in == nil {
		return nil
	}
	out := new(DecisionServiceComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddingSpec) DeepCopyInto(out *EmbeddingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddingSpec.
func (in *EmbeddingSpec) DeepCopy() *EmbeddingSpec {
	if in == nil {
		return nil
	}
	out := new(EmbeddingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FHIRTargetSpec) DeepCopyInto(out *FHIRTargetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FHIRTargetSpec.
func (in *FHIRTargetSpec) DeepCopy() *FHIRTargetSpec {
	if in == nil {
		return nil
	}
	out := new(FHIRTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMConfigSpec) DeepCopyInto(out *LLMConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMConfigSpec.
func (in *LLMConfigSpec) DeepCopy() *LLMConfigSpec {
	if in == nil {
		return nil
	}
	out := new(LLMConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilitySpec) DeepCopyInto(out *ObservabilitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilitySpec.
func (in *ObservabilitySpec) DeepCopy() *ObservabilitySpec {
	if in == nil {
		return nil
	}
	out := new(ObservabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineReference) DeepCopyInto(out *PipelineReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineReference.
func (in *PipelineReference) DeepCopy() *PipelineReference {
	if in == nil {
		return nil
	}
	out := new(PipelineReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineSandboxSpec) DeepCopyInto(out *PipelineSandboxSpec) {
	*out = *in
	out.Gateway = in.Gateway
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineSandboxSpec.
func (in *PipelineSandboxSpec) DeepCopy() *PipelineSandboxSpec {
	if in == nil {
		return nil
	}
	out := new(PipelineSandboxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PythonComponentSpec) DeepCopyInto(out *PythonComponentSpec) {
	*out = *in
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PythonComponentSpec.
func (in *PythonComponentSpec) DeepCopy() *PythonComponentSpec {
	if in == nil {
		return nil
	}
	out := new(PythonComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewerSpec) DeepCopyInto(out *ReviewerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewerSpec.
func (in *ReviewerSpec) DeepCopy() *ReviewerSpec {
	if in == nil {
		return nil
	}
	out := new(ReviewerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxGatewaySpec) DeepCopyInto(out *SandboxGatewaySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxGatewaySpec.
func (in *SandboxGatewaySpec) DeepCopy() *SandboxGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(SandboxGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxRequest) DeepCopyInto(out *SandboxRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxRequest.
func (in *SandboxRequest) DeepCopy() *SandboxRequest {
	if in == nil {
		return nil
	}
	out := new(SandboxRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxRequestList) DeepCopyInto(out *SandboxRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxRequestList.
func (in *SandboxRequestList) DeepCopy() *SandboxRequestList {
	if in == nil {
		return nil
	}
	out := new(SandboxRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxRequestSpec) DeepCopyInto(out *SandboxRequestSpec) {
	*out = *in
	out.Gateway = in.Gateway
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(v1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxRequestSpec.
func (in *SandboxRequestSpec) DeepCopy() *SandboxRequestSpec {
	if in == nil {
		return nil
	}
	out := new(SandboxRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxRequestStatus) DeepCopyInto(out *SandboxRequestStatus) {
	*out = *in
	out.Gateway = in.Gateway
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxRequestStatus.
func (in *SandboxRequestStatus) DeepCopy() *SandboxRequestStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxResources) DeepCopyInto(out *SandboxResources) {
	*out = *in
	if in.GPU != nil {
		in, out := &in.GPU, &out.GPU
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxResources.
func (in *SandboxResources) DeepCopy() *SandboxResources {
	if in == nil {
		return nil
	}
	out := new(SandboxResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadStatus) DeepCopyInto(out *WorkloadStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadStatus.
func (in *WorkloadStatus) DeepCopy() *WorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadStatus)
	in.DeepCopyInto(out)
	return out
}
