apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: HOME
              value: /tmp
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
